In [1]:
import requests
from bs4 import BeautifulSoup
import nltk
import pickle
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
import numpy as np
import pandas as pd
from datetime import datetime
from langdetect import detect
import os

In [23]:
df = pd.read_csv('..\datasets\df_toy.csv')
dir = r'..\datasets\requests'

In [24]:
df=df.drop(["Unnamed: 0"], axis = 1)

In [68]:
def request_to_row(request):
    with open("../datasets/requests/"+ request) as file:
        print(file)
        text = file.read()
        soup = BeautifulSoup(text)  
        full_text = soup.find("div",{"id": "jobDescriptionText"}).text
        if(detect(full_text) != 'en'):
            print(full_text[0:50]) #testing
            return 
    
        timestamp = None
        content = []
        title_location = soup.find("title").text
        title = title_location.split("-")[0]
        location = title_location.split("-")[1]
        url = soup.find_all("meta", {"id": "indeed-share-url"})
        url = str(url[0])[15:-25]
        
        country = url[8:10]

        list_elements = []
    
        divs = soup.find_all("div",{"id": "jobDescriptionText"})
        for div in divs:
            uls = div.find_all("ul")
            for ul in uls:
                for li in ul.find_all('li'):
                    list_elements.append(li.text)
    return [timestamp,url,title,location,country,full_text,list_elements]

In [70]:
df = pd.DataFrame(columns = ["dt","url","title","location","country","full_text","list_elements"])
for filename in os.listdir(dir):
    row_list = request_to_row(filename)
    foo.loc[len(foo)] = row_list

<_io.TextIOWrapper name='../datasets/requests/00281ab7d5a7749a' mode='r' encoding='cp1252'>

UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 112679: character maps to <undefined>

In [132]:
len(df_)

1637

In [131]:
df_.to_csv("df_europe")

In [150]:
df_dl=pd.read_csv('./datasets/data_scientist_united_states_job_postings_jobspikr.csv')
df_dl = df_dl.dropna(subset=['html_job_description'])
df_dl.head()

,crawl_timestamp,url,job_title,category,company_name,city,state,country,inferred_city,inferred_state,...,job_description,job_type,salary_offered,job_board,geo,cursor,contact_email,contact_phone_number,uniq_id,html_job_description
8338,2019-09-03 16:29:36 +0000,https://www.indeed.com/viewjob?jk=0ff929240cbd...,Data Scientist,Engineering-or-architecture,Datatron Technologies,Mountain View,CA,US,Mountain view,California,...,We are looking for a Data Scientist to apply d...,Undefined,NaN,indeed,usa,1567533631180639,NaN,NaN,6de263f8e3b53f2cb3ad2f56df9b2d6f,"<div id=""jobDescriptionText"" class=""jobsearch-..."
8339,2019-09-03 16:29:57 +0000,https://www.indeed.com/viewjob?jk=57d5bc547a93...,Data Scientist,Engineering-or-architecture,3T Biosciences,Menlo Park,CA,US,Menlo park,California,...,CULTURE:\n\nWe’re committed to making a differ...,Undefined,NaN,indeed,usa,1567533631641041,NaN,NaN,03831abc643392c3fc07543f81a2031f,"<div id=""jobDescriptionText"" class=""jobsearch-..."
8340,2019-09-03 15:36:16 +0000,https://www.indeed.com/viewjob?jk=9ba0c82d9eee...,"Data Scientist/Engineer (HDF, NiFi)",Construction-or-facilities,Novel Applications of Vital Information,Dulles,VA 20101,US,NaN,Virginia,...,"Data Scientist/Engineer (HDF, NiFi)\n\nLocatio...",Undefined,NaN,indeed,usa,1567533632291934,NaN,NaN,dc11fb4c640eb21e27754abd71430f41,"<div id=""jobDescriptionText"" class=""jobsearch-..."
8341,2019-09-03 16:31:44 +0000,https://www.indeed.com/viewjob?jk=6b46936a0aad...,Data Scientist,Engineering-or-architecture,4th-IR,New York,NY,US,New york,New york,...,"We’re looking for intelligent, creative indivi...",Undefined,NaN,indeed,usa,1567533632358051,NaN,NaN,363d6929ca85786a734812d0605df060,"<div id=""jobDescriptionText"" class=""jobsearch-..."
8342,2019-09-03 16:32:31 +0000,https://www.indeed.com/viewjob?jk=2064635d106d...,Data Scientist,Engineering-or-architecture,Social Science Research Solutions (SSRS),Glen Mills,PA,US,NaN,Pennsylvania,...,"SSRS Data Scientist\n\nSSRS, a leading data-dr...",Undefined,NaN,indeed,usa,1567533632670111,NaN,NaN,98dcc399714685995627bdf1e0d0dfca,"<div id=""jobDescriptionText"" class=""jobsearch-..."

In [169]:
df_dl=df_dl[["crawl_timestamp","url","job_title","inferred_city","job_description","html_job_description"]]#,axis=1)
df_dl.head()
#df_dl.columns = ['title','full_text','location']
countries = []
list_of_list_elements = []
for index, row in df_dl.iterrows():
    countries.append("us")
    soup = BeautifulSoup(row["html_job_description"])
    list_elements = []
    
    divs = soup.find_all("div",{"id": "jobDescriptionText"})
    for div in divs:
        uls = div.find_all("ul")
        for ul in uls:
            for li in ul.find_all('li'):
                list_elements.append(li.text)
    list_of_list_elements.append(list_elements)
df_dl["country"]=countries
df_dl["list_elements"] = list_of_list_elements
df_dl = df_dl.drop(["html_job_description"], axis = 1)
df_dl.columns = ["dt","url","title","location","full_text","country","list_elements"]
df_dl = df_dl.reindex(columns=["dt","url","title","location","country","full_text","list_elements"])

In [174]:
df_dl

,dt,url,title,location,full_text,country,list_elements
8338,2019-09-03 16:29:36 +0000,https://www.indeed.com/viewjob?jk=0ff929240cbd...,Data Scientist,Mountain view,We are looking for a Data Scientist to apply d...,us,"[Selecting features, building and optimizing m..."
8339,2019-09-03 16:29:57 +0000,https://www.indeed.com/viewjob?jk=57d5bc547a93...,Data Scientist,Menlo park,CULTURE:\n\nWe’re committed to making a differ...,us,"[\nBuilding, testing, and optimizing statistic..."
8340,2019-09-03 15:36:16 +0000,https://www.indeed.com/viewjob?jk=9ba0c82d9eee...,"Data Scientist/Engineer (HDF, NiFi)",NaN,"Data Scientist/Engineer (HDF, NiFi)\n\nLocatio...",us,"[U.S. Citizenship required, Must have current ..."
8341,2019-09-03 16:31:44 +0000,https://www.indeed.com/viewjob?jk=6b46936a0aad...,Data Scientist,New york,"We’re looking for intelligent, creative indivi...",us,[]
8342,2019-09-03 16:32:31 +0000,https://www.indeed.com/viewjob?jk=2064635d106d...,Data Scientist,NaN,"SSRS Data Scientist\n\nSSRS, a leading data-dr...",us,"[Use machine learning methods (e.g., cluster a..."
...,...,...,...,...,...,...,...
9994,2019-09-29 00:43:50 +0000,https://stackoverflow.com/jobs/293326,"Siri - Embedded Data Scientist, Data Organization",Pittsburgh,Job Summary: Would you like to play a part in ...,us,[]
9995,2019-09-29 00:55:15 +0000,https://stackoverflow.com/jobs/271829,Data Scientist,Columbus,Join Upstart and help build the future of cred...,us,[]
9996,2019-10-01 00:50:33 +0000,https://stackoverflow.com/jobs/283895,"Data Scientist, (Staff or Principal)",Santa clara,"Data Scientist, (Staff or Principal) at realto...",us,[]
9998,2019-09-27 00:41:31 +0000,https://stackoverflow.com/jobs/283895,"Data Scientist, (Staff or Principal)",Santa clara,"Data Scientist, (Staff or Principal) at realto...",us,[]
9999,2019-09-27 00:53:10 +0000,https://stackoverflow.com/jobs/283895,"Data Scientist, (Staff or Principal)",Santa clara,"Data Scientist, (Staff or Principal) at realto...",us,[]

In [172]:
df_full = df_.append(df_dl)

In [180]:
df_full = df_full.drop_duplicates(subset=['location','full_text'])

In [181]:
df_full.to_csv('df_full.csv')

In [182]:
len(df_full)

2633